default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: devtrain_development
  username: ccschmitz
  password:
  host: localhost
  port: 5432

test:
  <<: *default
  database: devtrain_test
  username: ccschmitz
  password:
  host: localhost
  port: 5432
