# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cfbfec43f56f68bd8aedded439dc183ed3e8d71cb1e2c486939fca3f5bf0679041a39a7296c19259e73594579b9ca3d1561a8287ed309f4e9d878dd4ca4f1fb

test:
  secret_key_base: 2385311e488a2ada41373bbd7c80846eb54a8e48ff548df995927b13bed3f2daab8806a25e85123723ee9ab702910de118f9229d9ceb822a5608738509522149

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
